apiVersion: v1
kind: Service
metadata:
  labels:
    run: payment-ms
  name: payment-ms
  namespace: totem
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
      nodePort: 31001
  selector:
    app: payment-ms