apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payment-ms-mongo
  namespace: payment-ms
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
