apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-ms
  namespace: totem
  labels:
    app: payment-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-ms
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: payment-ms
    spec:
      containers:
      - name: payment-ms
        envFrom:
        - configMapRef:
       # - secretRef:
            name: payment-ms-configmap
        image: andrauss/payment-ms:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
        workingDir: /var/www
      imagePullSecrets:
      - name: dockerhub
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /tmp
          type: Directory
        name: tmpdir
