apiVersion: v1
kind: PersistentVolume
metadata:
  name: payment-ms-mongo
  namespace: payment-ms
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/application"