version: "3.1"
services:
  payment-ms-mongo:
      build:
        context: .
        dockerfile: docker/database/Dockerfile
      container_name: payment-ms-mongo
      volumes:
        - ./docker/database/mongo:/application/
      environment:
        - MONGO_INITDB_ROOT_USERNAME=totem
        - MONGO_INITDB_ROOT_PASSWORD=totem
        - MONGODB_URI=mongodb://payment-ms-mongo:27017/totem-payments
      ports:
        - "27018:27017"
      networks:
        - totem

  payment-ms:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: payment-ms
    volumes:
      - ./docker/bin:/var/bin
    command: sh -c "npm install && chown -R www-data:www-data /var/www"
    ports:
      - "3002:3000"
    links:
      -   payment-ms-mongo
    networks:
      - totem

networks:
  totem:
#    external: true
    
volumes:
  dbdata:
    driver: local