apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-ms
  namespace: totem
  labels:
    app: payment-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-ms
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: payment-ms
    spec:
      containers:
      - name: payment-ms
        image: **LATEST_IMAGE
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: payment-ms-configmap
        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: payment-ms-secret
                key: host
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: payment-ms-secret
                key: port
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: payment-ms-secret
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: payment-ms-secret
                key: password
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
        workingDir: /app
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /tmp
          type: Directory
        name: tmpdir